typography_spectrum: 0.3620887896977365
color:
  brandStrength: 0.2576022916473448
  lightness: 0.607370032928884
  saturation: 0.7868062809575349
  rhythmicContrast: 0.2468105680309236
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.11205886770039797
name: Mark Site Testing Grid
navigation:
  - name: Marketing Agency
    url: 'http://www.marksite-agency.com'
    type: external
title: We make your business grow
